export const CLEAR_STATE = 'CLEAR_STATE'

export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_KEY = 'SET_USER_KEY'
export const UPDATE_USER = 'UPDATE_USER'
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE'

export const REORDER_ORDERS_LIST = 'REORDER_ORDERS_LIST'
export const MOVE_ORDER_LIST = 'MOVE_ORDER_LIST'

export const SET_MEALS_KEY = 'SET_MEALS_KEY'
export const ADD_MEAL_KEY = 'ADD_MEAL_KEY'
export const UPDATE_MEALS_BY_ID = 'UPDATE_MEALS_BY_ID'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_NOTIFY = 'SET_NOTIFY'

export const SET_CHEFS_KEY = 'SET_CHEFS_KEY'